"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

function sumeven_fibbonaci(limit)
    Fn = [0, 1]
    sum = 0
    
    while Fn[2] <= limit
        Fn[1],Fn[2] = Fn[2], Fn[1]+Fn[2]
        if Fn[2]%2 ==0
            sum += Fn[2]
        end
    end
    return sum
end

@assert sumeven_fibbonaci(50) == 44
@show sumeven_fibbonaci(4_000_000)
